blank_issues_enabled: false
contact_links:
  - name: 💬 Suporte ou dúvida geral
    url: https://github.com/rafaelcostappz/SEU-REPO/discussions
    about: Use esse link para perguntas, sugestões gerais ou discussões técnicas.
